#!/bin/bash

# init aplications
xsetroot -cursor_name left_ptr
sxhkd &
picom -b &


# set random wallpaper
randWallppr


# init polybar
polybar date &
sleep 1
polybar workSpaces &
sleep 1
polybar extra &
 

# bspwm configurations
bspc monitor -d 1 2 3 4
bspc config border_width	0
bspc config split_ratio		0.5
bspc config pointer_modifier	mod4

bspc config window_gap		15

bspc config top_padding		100
bspc config bottom_padding	100
bspc config left_padding	650
bspc config right_padding	650
 



# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner

 
